name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: make install  # Runs the 'make install' command to install dependencies

    - name: Start the server
      run: |
        make run &  # Start the server in the background
        echo $! > server_pid  # Save the server's PID to a file
        sleep 10  # Sleep for 10 seconds to ensure the server has time to start

    - name: Run tests
      run: make test  # Runs the 'make test' target from the Makefile

    - name: Stop the server
      if: always()
      run: |
        kill $(cat server_pid)  # Kill the server using the stored PID
