name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the version of Python you need

    - name: Install dependencies
      run: make install  # This runs `make install` to install dependencies

    - name: Start server
      run: |
        make run &  # Start the server in the background
        sleep 10    # Wait for 10 seconds to give the server time to start

    - name: Run tests
      run: make test  # Run your tests after the server has started

    - name: Stop server
      if: always()
      run: pkill -f "make run"  # Ensure the server stops after the workflow completes
